# Generated by Django 5.2 on 2025-04-21 15:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Description of the expense', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expense amount (e.g., in BRL)', max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date the expense occurred or was recorded')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date'],
            },
        ),
    ]
